=== BISONNL/KV1-index/xsd/kv1-index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (http://www.altova.com) by InTraffic B.V. (ACC ICT) -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright: Dit document is eigendom van Platform BISON onder de Stichting Connekt,                                                 -->
<!--            en wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl,                                                  -->
<!--            zie http://creativecommons.org/licences/by-nd/3.0/nl                                                                    -->
<!-- Opmerking: XSD betreft KV1 index. Met KV1 index is het mogelijk KV1 bestanden automatisch in te lezen/verwerken.                   -->
<!--            In de index wordt vastgelegd in welke volgorde de verschillende KV1 sets moeten worden verwerkt/ingelezen om tot een    -->
<!--            voor een volledige geldige dienstregeling. De KV1 index kan met verschillende versies van de Bison kv definitie worden  -->
<!--            gebruikt. Per setperiode wordt de vroegste ingangs/startdatum van de KV1 set in de index vastgelegd. Uit de informatie  -->
<!--            in de index kan worden afgeleid of een vorige KV1 set volledig of deels wordt vervangen of naast een voorgaande set     -->
<!--            geldig blijft.                                                                                                          -->
<!--                                                                                                                                    -->
<!-- Versie:  0.4 (concept) (28-01-2016)                                                                                                -->
<!--          0.5 15-02-16                                                                                                              -->
<!--          0.6 25-02-16                                                                                                              -->
<!--          0.7 29-02-16                                                                                                              -->
<!-- Historie:                                                                                                                          -->
<!--          0.4: initiële versie XSD, gebaseerd op versie zoals besproken in Bison WA op 1 oktober 2015                               -->
<!--          0.5: voorstel voor integratie met GVB versie KV1 index, incl. verwijzing naar ppt file                                    -->
<!--          0.6: Aangepast voorstel n.a.v. bespreking in KV1 werkgroep 18 febuari '16                                                 -->
<!--          0.7: Aangepast voorstel n.a.v. bespreking in KV1 werkgroep 29 febuari '16                                                 -->
<!--          0.8: Aangepast voorstel n.a.v. bespreking in AW 24-3-2016;  kv1/ppt versienummers zijn nu strings             -->
<!--          0.9: Aangepast voorstel n.a.v. document concept (c): velden nu conform document                                     -->
<!--          0.91: Aangepast voorstel n.a.v. document concept (d): alle velden in lowercase                                     -->
<!--                                                                                                                                    -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv1/msg" targetNamespace="http://bison.connekt.nl/tmi8/kv1/msg" elementFormDefault="qualified">
	<!-- KV1 index                                                                         	-->
	<!-- KV1 index wordt (optioneel) gelijktijdig met een KV1 dataset aangeleverd.         	-->
	<!-- De KV1-index bevat metadata over de KV1 dataset, waardoor ontvanger de            	-->
	<!-- mogelijkheid heeft de KV1 dataset automatisch te verwerken.                       	-->
	<!--    																			   	-->
	<!--  De KV1 index wordt samen met de KV1set en optioneel pptset op een ftp server     	-->
	<!--  van de ontvanger geplaatst													   	-->
	<!--  Het ontvangstproces bepaalt cyclisch of er nieuwe KV1 indexen klaar staan voor   	-->
	<!--  verwerking.    																    -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 	-->
	<!--                                                                         			-->
	<!-- De Setgeldigheidsperiode beschrijft de geldigheid van een kv1(-delta)   			-->
	<!-- Sleutel van een setgeldigheidsperiode: DataOwnerCode + setcode + index + versie  	-->
	<!--                                                                             		-->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 	-->
	<!--                                                                         			-->
	<!-- Het vastleggen van lijnen bij setgeldigheidsperiode is optioneel bij aanleveren 	-->
	<!-- van een kv1 baseline en verplicht bij KV1-planning delta om te bepalen op welke    -->
	<!-- lijnen de delta planning betrekking heeft                                     		-->
	<!--                                                                         			-->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -	-->
	<xs:element name="setgeldigheidsperiode">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tmi8:dataownercode"/>
				<xs:element ref="tmi8:setcode"/>
				<xs:element ref="tmi8:index"/>
				<xs:element ref="tmi8:versie"/>
				<xs:element ref="tmi8:publicatiedatum"/>
				<xs:element ref="tmi8:isgeldig"/>
				<xs:element ref="tmi8:startdatum"/>
				<xs:element ref="tmi8:einddatum"/>
				<xs:element ref="tmi8:isbaseline"/>
				<xs:element ref="tmi8:zipfile" minOccurs="0"/>
				<xs:element ref="tmi8:kv1dossier" minOccurs="0"/>
				<xs:element ref="tmi8:pptfile" minOccurs="0"/>
				<xs:element ref="tmi8:pptdossier" minOccurs="0"/>
				<xs:element ref="tmi8:lijnen" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Elementen                                                           -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:element name="dataownercode" type="xs:string">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Dit veld geeft de eigenaar van het bestand weer in de vorm van een code. Bijvoorbeeld “CXX” of “GVB”.
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="setcode" type="xs:string">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Dit veld geeft het gebied weer volgens indeling vervoerder voor een deel van zijn dienstregeling. 
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="index" type="xs:unsignedInt">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Dit is een nummer binnen hetindexbestand van een vervoerder. De index moet oplopend zijn, nummers behoeven niet aaneengesloten te zijn. Bij het bereiken van de max. waarde opnieuw beginnen bij 1.
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="versie" type="xs:unsignedInt">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Een gepubliceerde periode krijgt in eerste instantie altijd versienummer 1. Mocht er iets wijzigen in een KV1, dan wordt het versienummer opgehoogd. Bij het bereiken van de max. waarde opnieuw beginnen bij 1.   
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="publicatiedatum" type="xs:dateTime">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Dit is de tijdsaanduiding van het moment waarop deze versie van het bestand beschikbaar wordt gesteld aan afnemers.
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="isbaseline" type="xs:boolean">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Indicator die aangeeft of dit bestand de basisjaardienstregeling bevat (“true”) of een tijdelijke gedeeltelijke wijziging op de basisdienstregeling  (“false”). 
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="startdatum" type="xs:date">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                De startdatum is de vroegste operationele dag waarbinnen de KV1 geldig wordt. Deze startdatum kan de geldigheid van de operationele kalender in de KV1 set beperken.
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="einddatum" type="xs:date">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                De laatste operationele dag van de geldigheid van het KV1-bestand. Indien in de operationele kalender in de KV1-set een latere datum voorkomt dan “einddatum”, prevaleert de “einddatum” zoals opgenomen in de KV1-index.  
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="isgeldig" type="xs:boolean">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Veld dat aangeeft of het bestand geldig is. In principe is dit veld altijd gevuld met “true”; in de situatie dat en eerder gepubliceerde afwijkende delta planning ingetrokken moet worden, bijv. omdat een geplande omleiding niet doorgaat, zal dit veld de waarde “false” krijgen. Bij een waarde 'false' wordt de eerder gepubliceerde KV1 set met dezelfde dataownercode, setcode, index en versienummer ingetrokken.  
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="zipfile" type="xs:string">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Dit is de verwijzing naar de bestandsnaam van het ZIP-bestand. Conventie: KV1_[DataOwnerCode]_[setcode]_[Index]_[Versie].zip  
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="kv1dossier">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Versienummer van het BISON-koppelvlak. Dit versienummer wordt gebruikt om KV1-data met de juiste BISON-koppelvlakdefinitie te valideren en in te laden.
            </xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pptfile" type="xs:string">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Dit is de verwijzing naar de bestandsnaam van het PPT-bestand.
            </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="pptdossier">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
                Versienummer van het BISON-ppt koppelvlak. 
            </xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="lijnen">
		<!--Lijnen: geeft aan welke LinePlanningNumbers in de set zitten -->
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tmi8:lineplanningnumber" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lineplanningnumber" type="xs:string">
		<xs:annotation>
			<xs:documentation xml:lang="nl">
               LinePlanningnumber, unieke systeemlijnnummer in domein vervoerder 
            </xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== BISONNL/KV1-index/xml/KV1 index VB4.xml
<?xml version="1.0" encoding="UTF-8"?>
<tmi8:setgeldigheidsperiode xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv1/msg kv1-index.xsd"  xmlns:tmi8="http://bison.connekt.nl/tmi8/kv1/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<!--Delta planning voor de lijnen 17365 en 17400 uit de setgroep ZHN van 1 juni - 15 juli 2015> -->
        <tmi8:dataownercode>ARR</tmi8:dataownercode>
		<tmi8:setcode>ZHN</tmi8:setcode>
        <tmi8:index>3</tmi8:index>
        <tmi8:versie>1</tmi8:versie>
        <tmi8:publicatiedatum>2015-05-10T04:55:00</tmi8:publicatiedatum>
<tmi8:isgeldig>true</tmi8:isgeldig>        <tmi8:startdatum>2015-06-01</tmi8:startdatum>
        <tmi8:einddatum>2015-07-15</tmi8:einddatum>
        <tmi8:isbaseline>false</tmi8:isbaseline>
        
        <tmi8:zipfile>KV1_ARR_ZHN_3_1.zip</tmi8:zipfile>
        <tmi8:kv1dossier>8.1.1.0</tmi8:kv1dossier>
        <tmi8:lijnen>
        	<tmi8:lineplanningnumber>17365</tmi8:lineplanningnumber>
        	<tmi8:lineplanningnumber>17400</tmi8:lineplanningnumber>
        </tmi8:lijnen>	
    </tmi8:setgeldigheidsperiode>

=== BISONNL/KV1-index/xml/KV1 index VB3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tmi8:setgeldigheidsperiode xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv1/msg kv1-index.xsd" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv1/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!--In setgroep BW vervallen lijnen 23301 en 23302 miv 1 februari 2015 ==> nieuwe baseline vervangt oude> -->
	<tmi8:dataownercode>ARR</tmi8:dataownercode>
	<tmi8:setcode>BW</tmi8:setcode>
	<tmi8:index>2</tmi8:index>
	<tmi8:versie>1</tmi8:versie>
	<tmi8:publicatiedatum>2015-01-15T15:07:57</tmi8:publicatiedatum>
	<tmi8:isgeldig>true</tmi8:isgeldig>
	<tmi8:startdatum>2015-02-01</tmi8:startdatum>
	<tmi8:einddatum>2015-12-12</tmi8:einddatum>
	<tmi8:isbaseline>true</tmi8:isbaseline>
	<tmi8:zipfile>KV1_ARR_BW_2_1.zip</tmi8:zipfile>
	<tmi8:kv1dossier>8.1.1.0</tmi8:kv1dossier>
</tmi8:setgeldigheidsperiode>

=== BISONNL/KV1-index/xml/KV1 index VB5.xml
<?xml version="1.0" encoding="UTF-8"?>
<tmi8:setgeldigheidsperiode xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv1/msg kv1-index.xsd" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv1/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!--Delta planning voor lijn 17400 wordt ingetrokken voor ingangsdatum 1 juni 2015>-->
	<!--Merk op dat hiermee ook lijn 17365 hier wordt ingetrokken, in nieuwe delta planning opnieuw aanbieden>  -->
	<tmi8:dataownercode>ARR</tmi8:dataownercode>
	<tmi8:setcode>ZHN</tmi8:setcode>
	<tmi8:index>3</tmi8:index>
	<tmi8:versie>1</tmi8:versie>
	<tmi8:publicatiedatum>2015-05-29T09:55:00</tmi8:publicatiedatum>
	<tmi8:isgeldig>false</tmi8:isgeldig>
	<tmi8:startdatum>2016-03-29</tmi8:startdatum>
	<tmi8:einddatum>2016-03-29</tmi8:einddatum>
	<tmi8:isbaseline>false</tmi8:isbaseline>
</tmi8:setgeldigheidsperiode>

=== BISONNL/KV1-index/xml/KV1 index XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!-- Voorbeeldbestand van KV1 index -->
<tmi8:setgeldigheidsperiode xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv1/msg kv1-index.xsd" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv1/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tmi8:dataownercode>DataOwnerCodeVanVervoerder</tmi8:dataownercode>
	<tmi8:setcode>SetCodeVanVervoerder</tmi8:setcode>
	<tmi8:index>999999999</tmi8:index>
	<tmi8:versie>0</tmi8:versie>
	<tmi8:publicatiedatum>2001-12-17T09:30:47Z</tmi8:publicatiedatum>
	<tmi8:isgeldig>true</tmi8:isgeldig>
	<tmi8:startdatum>2016-03-07</tmi8:startdatum>
	<tmi8:einddatum>2016-03-07</tmi8:einddatum>
	<tmi8:isbaseline>0</tmi8:isbaseline>
	<tmi8:zipfile>BestandsNaam.zip</tmi8:zipfile>
	<tmi8:kv1dossier>kv1 versie nummer w.x.y.z 8.1.2.0</tmi8:kv1dossier>
	<tmi8:pptfile>BestandsNaam</tmi8:pptfile>
	<tmi8:pptdossier>ppt versie nummer w.x.y.z 8.1.2.0</tmi8:pptdossier>
	<tmi8:lijnen>
		<tmi8:lineplanningnumber>EenLijn</tmi8:lineplanningnumber>
		<tmi8:lineplanningnumber>EenAndereLijn</tmi8:lineplanningnumber>
	</tmi8:lijnen>
</tmi8:setgeldigheidsperiode>
